# Xarray
## Paul Eldridge

Xarray is a python package that is great for working with multi-dimensional arrays. It is great for working with netCDF files.

In [3]:
import datetime
import numpy as np
import pandas as pd
import xarray as xr


### Since this class is based off of the geosciences, we will use a geoscience example. First, we will generate a random temperature dataset, in Kelvin, using numpy

In [6]:
data = 273 + np.random.randn(5, 3, 4) # Creating random "temperatures"
data

array([[[273.6276138 , 272.38656799, 274.26968778, 275.37802285],
        [272.69200018, 273.28536818, 272.88865279, 272.5870791 ],
        [272.15289789, 272.76111158, 274.26321078, 270.686693  ]],

       [[272.95691258, 272.32355586, 273.83247776, 273.06207312],
        [271.72048339, 273.10794271, 273.554869  , 273.27342346],
        [270.4025347 , 271.54893124, 274.81983597, 272.57025397]],

       [[271.20032766, 272.8855977 , 272.613939  , 272.29489548],
        [273.18285194, 272.4851436 , 273.74161712, 274.25606379],
        [273.3037821 , 271.74287482, 271.72422839, 271.4740035 ]],

       [[272.53933419, 272.14297363, 273.06960744, 273.37355491],
        [271.85167663, 274.62733533, 273.49968885, 271.98429329],
        [273.55391066, 272.61100173, 272.72590508, 273.89568052]],

       [[273.33813296, 273.56308935, 271.56004419, 273.60148362],
        [272.22217027, 273.75816271, 271.89071361, 274.97672194],
        [273.03118213, 271.18603253, 271.90092721, 273.75082201]]])

### This dataset is only a numpy array at the moment, so we will need to cast it into an xarray "data array"

In [5]:
temps = xr.DataArray(data) # Creation of a DataArray
temps

<xarray.DataArray (dim_0: 5, dim_1: 3, dim_2: 4)>
array([[[273.25176804, 272.30014786, 273.43770817, 273.13983703],
        [273.58008101, 273.65357867, 271.35394756, 273.46147697],
        [273.59528396, 273.44163772, 273.1854065 , 272.6952095 ]],

       [[273.57178533, 271.86055494, 273.95073321, 273.86602312],
        [272.02904729, 273.14542483, 273.00506049, 272.58839249],
        [273.73807058, 273.18290126, 273.44194619, 273.85040743]],

       [[272.83600415, 273.39498652, 273.84317065, 273.32062328],
        [273.7263657 , 274.4471619 , 273.30000637, 272.15693719],
        [273.10938496, 272.21838329, 273.96972371, 274.29380081]],

       [[272.61788151, 274.62190823, 273.41683042, 272.29571591],
        [274.65449005, 274.78809935, 273.42052577, 273.06209052],
        [271.48386641, 273.07261607, 274.23120133, 274.26295153]],

       [[273.90418874, 273.16424486, 273.53222439, 271.89582624],
        [273.83638711, 271.95879419, 275.08720762, 272.41894845],
        [274.25420988, 273.6100645 , 272.99793238, 274.27621347]]])
Dimensions without coordinates: dim_0, dim_1, dim_2

# Next, we will assign dimension names to our data array. This is where Xarray data arrays begin to shine over numpy arrays, as this isn't something we can do with numpy arrays.

In [7]:
temps = xr.DataArray(data, dims=['time', 'lat', 'lon']) # Assigning dimension names
temps

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[273.6276138 , 272.38656799, 274.26968778, 275.37802285],
        [272.69200018, 273.28536818, 272.88865279, 272.5870791 ],
        [272.15289789, 272.76111158, 274.26321078, 270.686693  ]],

       [[272.95691258, 272.32355586, 273.83247776, 273.06207312],
        [271.72048339, 273.10794271, 273.554869  , 273.27342346],
        [270.4025347 , 271.54893124, 274.81983597, 272.57025397]],

       [[271.20032766, 272.8855977 , 272.613939  , 272.29489548],
        [273.18285194, 272.4851436 , 273.74161712, 274.25606379],
        [273.3037821 , 271.74287482, 271.72422839, 271.4740035 ]],

       [[272.53933419, 272.14297363, 273.06960744, 273.37355491],
        [271.85167663, 274.62733533, 273.49968885, 271.98429329],
        [273.55391066, 272.61100173, 272.72590508, 273.89568052]],

       [[273.33813296, 273.56308935, 271.56004419, 273.60148362],
        [272.22217027, 273.75816271, 271.89071361, 274.97672194],
        [273.03118213, 271.18603253, 271.90092721, 273.75082201]]])
Dimensions without coordinates: time, lat, lon

# Xarray is great with "n-dimension" arrays"; in our use case, these dimensions will usually be time, latitude, and longitude. We will also store one or more variables that will be plotted for some latitude and longitude at some time. We are creating, in a sense, a "slideshow" of graphs. 

### Now, we will make spacetime coordinates. The times will be handled using pandas and datetime, and the space (lat/lons) will be done with numpy. We will then add this to our Xarray Dataarray.

In [8]:
times = pd.date_range('2018-01-01', periods=5) # creating an array of datetimes
times

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='D')

In [11]:
lons = np.linspace(-120, -60, 4) # creating a sample of longitudes. The last argument represents the increments, 
                                 # so we end up with 4 longitude points and 3 latitude points. 
lats = np.linspace(25, 55, 3) # creating a sample of latitudes

temps = xr.DataArray(data, coords=[times, lats, lons], 
                     dims=['time', 'lat', 'lon'])
# creating a DataArray with dimensions and coordinates associated with the temperature values

temps

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[273.6276138 , 272.38656799, 274.26968778, 275.37802285],
        [272.69200018, 273.28536818, 272.88865279, 272.5870791 ],
        [272.15289789, 272.76111158, 274.26321078, 270.686693  ]],

       [[272.95691258, 272.32355586, 273.83247776, 273.06207312],
        [271.72048339, 273.10794271, 273.554869  , 273.27342346],
        [270.4025347 , 271.54893124, 274.81983597, 272.57025397]],

       [[271.20032766, 272.8855977 , 272.613939  , 272.29489548],
        [273.18285194, 272.4851436 , 273.74161712, 274.25606379],
        [273.3037821 , 271.74287482, 271.72422839, 271.4740035 ]],

       [[272.53933419, 272.14297363, 273.06960744, 273.37355491],
        [271.85167663, 274.62733533, 273.49968885, 271.98429329],
        [273.55391066, 272.61100173, 272.72590508, 273.89568052]],

       [[273.33813296, 273.56308935, 271.56004419, 273.60148362],
        [272.22217027, 273.75816271, 271.89071361, 274.97672194],
        [273.03118213, 271.18603253, 271.90092721, 273.75082201]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0

### Next, we will add attributes to our Data Array. We want to know what our data means. 

In [12]:
temps.attrs['units'] = 'kelvin'
temps.attrs['standard_name'] = 'air_temperature'
# Creating ttributes (metadata)

temps

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[273.6276138 , 272.38656799, 274.26968778, 275.37802285],
        [272.69200018, 273.28536818, 272.88865279, 272.5870791 ],
        [272.15289789, 272.76111158, 274.26321078, 270.686693  ]],

       [[272.95691258, 272.32355586, 273.83247776, 273.06207312],
        [271.72048339, 273.10794271, 273.554869  , 273.27342346],
        [270.4025347 , 271.54893124, 274.81983597, 272.57025397]],

       [[271.20032766, 272.8855977 , 272.613939  , 272.29489548],
        [273.18285194, 272.4851436 , 273.74161712, 274.25606379],
        [273.3037821 , 271.74287482, 271.72422839, 271.4740035 ]],

       [[272.53933419, 272.14297363, 273.06960744, 273.37355491],
        [271.85167663, 274.62733533, 273.49968885, 271.98429329],
        [273.55391066, 272.61100173, 272.72590508, 273.89568052]],

       [[273.33813296, 273.56308935, 271.56004419, 273.60148362],
        [272.22217027, 273.75816271, 271.89071361, 274.97672194],
        [273.03118213, 271.18603253, 271.90092721, 273.75082201]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

### Like numpy, it is easy to perform mathematical operations in Xarray. Here, we convert our temperatures from Kelvin to Celcius. Notice that the attributes do not carry over.

In [14]:
tempC = temps - 273.15 # Converting from kelvin to celcius
tempC

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[ 0.4776138 , -0.76343201,  1.11968778,  2.22802285],
        [-0.45799982,  0.13536818, -0.26134721, -0.5629209 ],
        [-0.99710211, -0.38888842,  1.11321078, -2.463307  ]],

       [[-0.19308742, -0.82644414,  0.68247776, -0.08792688],
        [-1.42951661, -0.04205729,  0.404869  ,  0.12342346],
        [-2.7474653 , -1.60106876,  1.66983597, -0.57974603]],

       [[-1.94967234, -0.2644023 , -0.536061  , -0.85510452],
        [ 0.03285194, -0.6648564 ,  0.59161712,  1.10606379],
        [ 0.1537821 , -1.40712518, -1.42577161, -1.6759965 ]],

       [[-0.61066581, -1.00702637, -0.08039256,  0.22355491],
        [-1.29832337,  1.47733533,  0.34968885, -1.16570671],
        [ 0.40391066, -0.53899827, -0.42409492,  0.74568052]],

       [[ 0.18813296,  0.41308935, -1.58995581,  0.45148362],
        [-0.92782973,  0.60816271, -1.25928639,  1.82672194],
        [-0.11881787, -1.96396747, -1.24907279,  0.60082201]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0

# Now, we will another dimension to our data array. Let's do pressures. 

In [15]:
pressureRand = 1013.25 + 2 * np.random.randn(5, 3, 4)
pressures = xr.DataArray(pressureRand, coords= [times, lats, lons],
                        dims= ['time', 'lat', 'lon']
                        )
pressures.attrs['units'] = 'hPa'
pressures.attrs['standard_name'] = 'air_pressure'

# Creating a dataset with pressures

pressures

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[1013.93576774, 1012.0345241 , 1010.16586385, 1012.57330766],
        [1012.21204956, 1013.96443048, 1010.16807333, 1013.98050349],
        [1013.68400161, 1011.70363186, 1010.77848992, 1014.99998686]],

       [[1014.73157597, 1009.9945212 , 1013.18795141, 1011.47610639],
        [1012.76727374, 1011.27868544, 1012.93509681, 1012.40426607],
        [1013.65120875, 1011.45792212, 1017.89973106, 1012.49931165]],

       [[1010.7468606 , 1010.32385144, 1011.94474711, 1013.59823136],
        [1012.45818853, 1014.35696579, 1009.89955985, 1012.37543659],
        [1014.78744282, 1015.04900205, 1011.72048895, 1014.32108192]],

       [[1012.52136134, 1014.9620144 , 1014.81802433, 1012.09035762],
        [1011.78102021, 1008.29798705, 1012.77210206, 1014.23918975],
        [1011.07581909, 1010.85923375, 1012.21401264, 1017.73809926]],

       [[1012.66159401, 1013.57950555, 1012.57401742, 1010.90245315],
        [1015.25856185, 1009.8682156 , 1015.99182392, 1012.72610875],
        [1014.2833763 , 1011.89570425, 1009.83089233, 1015.4747839 ]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

In [17]:
ds = xr.Dataset(data_vars= {'Temperatures': temps, 'Pressures': pressures})
ds

# Combining the DataArrays into a Dataset. These arrays share the coordinates.

<xarray.Dataset>
Dimensions:       (time: 5, lat: 3, lon: 4)
Coordinates:
  * time          (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat           (lat) float64 25.0 40.0 55.0
  * lon           (lon) float64 -120.0 -100.0 -80.0 -60.0
Data variables:
    Temperatures  (time, lat, lon) float64 273.6 272.4 274.3 ... 271.9 273.8
    Pressures     (time, lat, lon) float64 1.014e+03 1.012e+03 ... 1.015e+03

### If we want to examine one of our variables, we can call that specific array in the following ways:

In [18]:
ds.Pressures

'''OR''' # Two ways to call an array

ds['Pressures']

<xarray.DataArray 'Pressures' (time: 5, lat: 3, lon: 4)>
array([[[1013.93576774, 1012.0345241 , 1010.16586385, 1012.57330766],
        [1012.21204956, 1013.96443048, 1010.16807333, 1013.98050349],
        [1013.68400161, 1011.70363186, 1010.77848992, 1014.99998686]],

       [[1014.73157597, 1009.9945212 , 1013.18795141, 1011.47610639],
        [1012.76727374, 1011.27868544, 1012.93509681, 1012.40426607],
        [1013.65120875, 1011.45792212, 1017.89973106, 1012.49931165]],

       [[1010.7468606 , 1010.32385144, 1011.94474711, 1013.59823136],
        [1012.45818853, 1014.35696579, 1009.89955985, 1012.37543659],
        [1014.78744282, 1015.04900205, 1011.72048895, 1014.32108192]],

       [[1012.52136134, 1014.9620144 , 1014.81802433, 1012.09035762],
        [1011.78102021, 1008.29798705, 1012.77210206, 1014.23918975],
        [1011.07581909, 1010.85923375, 1012.21401264, 1017.73809926]],

       [[1012.66159401, 1013.57950555, 1012.57401742, 1010.90245315],
        [1015.25856185, 1009.8682156 , 1015.99182392, 1012.72610875],
        [1014.2833763 , 1011.89570425, 1009.83089233, 1015.4747839 ]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

# What if we want to analyze some variable at a specific time or place?

In [19]:
named_selection = temps.sel(time= '2018-01-02')
named_selection
# Using .sel() to select data based on coordinate values. This takes at least
# 1 named coordinate and returns data matching said coordinates.

<xarray.DataArray (lat: 3, lon: 4)>
array([[272.95691258, 272.32355586, 273.83247776, 273.06207312],
       [271.72048339, 273.10794271, 273.554869  , 273.27342346],
       [270.4025347 , 271.54893124, 274.81983597, 272.57025397]])
Coordinates:
    time     datetime64[ns] 2018-01-02
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [22]:
temps.sel(time= slice('2018-01-01', '2018-01-03'), lon= slice(-110, -70), lat= slice(25, 45))

# In this example,, we are slicing along coordinates for a specific range of times, lats, and lons.


<xarray.DataArray (time: 3, lat: 2, lon: 2)>
array([[[272.38656799, 274.26968778],
        [273.28536818, 272.88865279]],

       [[272.32355586, 273.83247776],
        [273.10794271, 273.554869  ]],

       [[272.8855977 , 272.613939  ],
        [272.4851436 , 273.74161712]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 2018-01-03
  * lat      (lat) float64 25.0 40.0
  * lon      (lon) float64 -100.0 -80.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [23]:
temps.loc['2018-01-01']

<xarray.DataArray (lat: 3, lon: 4)>
array([[273.6276138 , 272.38656799, 274.26968778, 275.37802285],
       [272.69200018, 273.28536818, 272.88865279, 272.5870791 ],
       [272.15289789, 272.76111158, 274.26321078, 270.686693  ]])
Coordinates:
    time     datetime64[ns] 2018-01-01
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [24]:
temps.loc['2018-01-01':'2018-01-01', 23:45, -110:-70]

# Another selection method, .loc[], similar to pandas

<xarray.DataArray (time: 1, lat: 2, lon: 2)>
array([[[272.38656799, 274.26968778],
        [273.28536818, 272.88865279]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01
  * lat      (lat) float64 25.0 40.0
  * lon      (lon) float64 -100.0 -80.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

# Like pandas, we can import files directly into a dataset. These files will typically be netcdf files.

In [ ]:
filepath = 'NOAAGlobalTemp_v5.0.0_gridded_s188001_e202212_c20230108T133308.nc'

ds = xr.open_dataset(filepath)
ds

# Importing a dataset into Xarray.