# Xarray
## Paul Eldridge

Xarray is a python package that is great for working with multi-dimensional arrays. It is great for working with netCDF files.

In [2]:
import datetime
import numpy as np
import pandas as pd
import xarray as xr


In [5]:
data = 273 + np.random.randn(5, 3, 4) # Creating random "temperatures"
data

array([[[273.28239724, 272.39681535, 272.83836254, 272.01551886],
        [272.50156357, 273.21128587, 274.59331446, 272.68284241],
        [272.76197732, 273.71141569, 272.89262794, 272.63358187]],

       [[271.01922214, 273.25043174, 273.61887705, 272.83974387],
        [273.04405168, 271.65286474, 273.56231077, 273.33372038],
        [273.46419864, 271.71473318, 273.64877137, 273.49002289]],

       [[273.22094163, 272.07816224, 271.74932835, 273.57780827],
        [273.02207703, 272.69236729, 272.56966262, 271.64117828],
        [271.1664246 , 273.70446373, 272.99368795, 274.48808177]],

       [[274.61938129, 272.97288639, 272.97484997, 273.07252471],
        [274.44866978, 273.66325816, 273.02326078, 272.98514814],
        [271.68265849, 272.97898421, 274.08794344, 273.83134043]],

       [[272.5630241 , 270.6628183 , 272.15086606, 273.01293687],
        [273.09927927, 274.60739091, 272.1160282 , 274.75026659],
        [274.59332496, 273.23106199, 272.78791382, 272.29561093]]])

In [6]:
temps = xr.DataArray(data) # Creation of a DataArray
temps

<xarray.DataArray (dim_0: 5, dim_1: 3, dim_2: 4)>
array([[[273.28239724, 272.39681535, 272.83836254, 272.01551886],
        [272.50156357, 273.21128587, 274.59331446, 272.68284241],
        [272.76197732, 273.71141569, 272.89262794, 272.63358187]],

       [[271.01922214, 273.25043174, 273.61887705, 272.83974387],
        [273.04405168, 271.65286474, 273.56231077, 273.33372038],
        [273.46419864, 271.71473318, 273.64877137, 273.49002289]],

       [[273.22094163, 272.07816224, 271.74932835, 273.57780827],
        [273.02207703, 272.69236729, 272.56966262, 271.64117828],
        [271.1664246 , 273.70446373, 272.99368795, 274.48808177]],

       [[274.61938129, 272.97288639, 272.97484997, 273.07252471],
        [274.44866978, 273.66325816, 273.02326078, 272.98514814],
        [271.68265849, 272.97898421, 274.08794344, 273.83134043]],

       [[272.5630241 , 270.6628183 , 272.15086606, 273.01293687],
        [273.09927927, 274.60739091, 272.1160282 , 274.75026659],
        [274.59332496, 273.23106199, 272.78791382, 272.29561093]]])
Dimensions without coordinates: dim_0, dim_1, dim_2

In [29]:
temps = xr.DataArray(data, dims=['time', 'lat', 'lon']) # Assigning dimension names
temps

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[273.28239724, 272.39681535, 272.83836254, 272.01551886],
        [272.50156357, 273.21128587, 274.59331446, 272.68284241],
        [272.76197732, 273.71141569, 272.89262794, 272.63358187]],

       [[271.01922214, 273.25043174, 273.61887705, 272.83974387],
        [273.04405168, 271.65286474, 273.56231077, 273.33372038],
        [273.46419864, 271.71473318, 273.64877137, 273.49002289]],

       [[273.22094163, 272.07816224, 271.74932835, 273.57780827],
        [273.02207703, 272.69236729, 272.56966262, 271.64117828],
        [271.1664246 , 273.70446373, 272.99368795, 274.48808177]],

       [[274.61938129, 272.97288639, 272.97484997, 273.07252471],
        [274.44866978, 273.66325816, 273.02326078, 272.98514814],
        [271.68265849, 272.97898421, 274.08794344, 273.83134043]],

       [[272.5630241 , 270.6628183 , 272.15086606, 273.01293687],
        [273.09927927, 274.60739091, 272.1160282 , 274.75026659],
        [274.59332496, 273.23106199, 272.78791382, 272.29561093]]])
Dimensions without coordinates: time, lat, lon

In [30]:
times = pd.date_range('2018-01-01', periods=5) # creating an array of datetimes
times

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='D')

In [32]:
lons = np.linspace(-120, -60, 4) # creating a sample of longitudes
lats = np.linspace(25, 55, 3) # creating a sample of latitudes

temps = xr.DataArray(data, coords=[times, lats, lons], 
                     dims=['time', 'lat', 'lon'])
# creating a DataArray with dimensions and coordinates associated with the temperature values

temps

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[273.28239724, 272.39681535, 272.83836254, 272.01551886],
        [272.50156357, 273.21128587, 274.59331446, 272.68284241],
        [272.76197732, 273.71141569, 272.89262794, 272.63358187]],

       [[271.01922214, 273.25043174, 273.61887705, 272.83974387],
        [273.04405168, 271.65286474, 273.56231077, 273.33372038],
        [273.46419864, 271.71473318, 273.64877137, 273.49002289]],

       [[273.22094163, 272.07816224, 271.74932835, 273.57780827],
        [273.02207703, 272.69236729, 272.56966262, 271.64117828],
        [271.1664246 , 273.70446373, 272.99368795, 274.48808177]],

       [[274.61938129, 272.97288639, 272.97484997, 273.07252471],
        [274.44866978, 273.66325816, 273.02326078, 272.98514814],
        [271.68265849, 272.97898421, 274.08794344, 273.83134043]],

       [[272.5630241 , 270.6628183 , 272.15086606, 273.01293687],
        [273.09927927, 274.60739091, 272.1160282 , 274.75026659],
        [274.59332496, 273.23106199, 272.78791382, 272.29561093]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0

In [33]:
temps.attrs['units'] = 'kelvin'
temps.attrs['standard_name'] = 'air_temperature'
# Creating ttributes (metadata)

temps

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[273.28239724, 272.39681535, 272.83836254, 272.01551886],
        [272.50156357, 273.21128587, 274.59331446, 272.68284241],
        [272.76197732, 273.71141569, 272.89262794, 272.63358187]],

       [[271.01922214, 273.25043174, 273.61887705, 272.83974387],
        [273.04405168, 271.65286474, 273.56231077, 273.33372038],
        [273.46419864, 271.71473318, 273.64877137, 273.49002289]],

       [[273.22094163, 272.07816224, 271.74932835, 273.57780827],
        [273.02207703, 272.69236729, 272.56966262, 271.64117828],
        [271.1664246 , 273.70446373, 272.99368795, 274.48808177]],

       [[274.61938129, 272.97288639, 272.97484997, 273.07252471],
        [274.44866978, 273.66325816, 273.02326078, 272.98514814],
        [271.68265849, 272.97898421, 274.08794344, 273.83134043]],

       [[272.5630241 , 270.6628183 , 272.15086606, 273.01293687],
        [273.09927927, 274.60739091, 272.1160282 , 274.75026659],
        [274.59332496, 273.23106199, 272.78791382, 272.29561093]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [34]:
tempC = temps - 273.15 # Converting from kelvin to celcius
tempC

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[ 0.13239724, -0.75318465, -0.31163746, -1.13448114],
        [-0.64843643,  0.06128587,  1.44331446, -0.46715759],
        [-0.38802268,  0.56141569, -0.25737206, -0.51641813]],

       [[-2.13077786,  0.10043174,  0.46887705, -0.31025613],
        [-0.10594832, -1.49713526,  0.41231077,  0.18372038],
        [ 0.31419864, -1.43526682,  0.49877137,  0.34002289]],

       [[ 0.07094163, -1.07183776, -1.40067165,  0.42780827],
        [-0.12792297, -0.45763271, -0.58033738, -1.50882172],
        [-1.9835754 ,  0.55446373, -0.15631205,  1.33808177]],

       [[ 1.46938129, -0.17711361, -0.17515003, -0.07747529],
        [ 1.29866978,  0.51325816, -0.12673922, -0.16485186],
        [-1.46734151, -0.17101579,  0.93794344,  0.68134043]],

       [[-0.5869759 , -2.4871817 , -0.99913394, -0.13706313],
        [-0.05072073,  1.45739091, -1.0339718 ,  1.60026659],
        [ 1.44332496,  0.08106199, -0.36208618, -0.85438907]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0

In [35]:
pressureRand = 1013.25 + 2 * np.random.randn(5, 3, 4)
pressures = xr.DataArray(pressureRand, coords= [times, lats, lons],
                        dims= ['time', 'lat', 'lon']
                        )
pressures.attrs['units'] = 'hPa'
pressures.attrs['standard_name'] = 'air_pressure'

# Creating a dataset with pressures

pressures

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[1014.58464713, 1015.39170181, 1015.42787944, 1011.62396968],
        [1010.16972432, 1011.77793234, 1016.93067585, 1013.21259258],
        [1014.5321931 , 1013.85010621, 1009.37379068, 1011.60743987]],

       [[1016.14242224, 1010.32707859, 1012.06796367, 1016.40633143],
        [1015.20661029, 1013.69668278, 1012.77363982, 1009.9642707 ],
        [1011.55020134, 1014.12328521, 1010.62283707, 1013.84873869]],

       [[1012.22280882, 1013.81718827, 1010.11942618, 1014.47296497],
        [1015.52724228, 1013.64987812, 1014.60438346, 1014.80083918],
        [1018.26562911, 1014.12294633, 1020.59203014, 1015.62677   ]],

       [[1014.90579243, 1011.76844059, 1015.2609588 , 1011.34257804],
        [1013.96184022, 1013.53961123, 1013.51574041, 1011.90345038],
        [1014.73537204, 1012.07217697, 1010.88977935, 1013.52115152]],

       [[1014.5346979 , 1012.99797493, 1011.80784613, 1011.99872311],
        [1015.10907083, 1013.88309907, 1015.05618316, 1013.53284177],
        [1015.87207527, 1015.59608272, 1015.64496147, 1014.64948099]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

In [36]:
ds = xr.Dataset(data_vars= {'Temperatures': temps, 'Pressures': pressures})
ds

# Combining the DataArrays into a Dataset. These arrays share the coordinates.

<xarray.Dataset>
Dimensions:       (time: 5, lat: 3, lon: 4)
Coordinates:
  * time          (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat           (lat) float64 25.0 40.0 55.0
  * lon           (lon) float64 -120.0 -100.0 -80.0 -60.0
Data variables:
    Temperatures  (time, lat, lon) float64 273.3 272.4 272.8 ... 272.8 272.3
    Pressures     (time, lat, lon) float64 1.015e+03 1.015e+03 ... 1.015e+03

In [37]:
ds.Pressures

'''OR''' # Two ways to call an array

ds['Pressures']

<xarray.DataArray 'Pressures' (time: 5, lat: 3, lon: 4)>
array([[[1014.58464713, 1015.39170181, 1015.42787944, 1011.62396968],
        [1010.16972432, 1011.77793234, 1016.93067585, 1013.21259258],
        [1014.5321931 , 1013.85010621, 1009.37379068, 1011.60743987]],

       [[1016.14242224, 1010.32707859, 1012.06796367, 1016.40633143],
        [1015.20661029, 1013.69668278, 1012.77363982, 1009.9642707 ],
        [1011.55020134, 1014.12328521, 1010.62283707, 1013.84873869]],

       [[1012.22280882, 1013.81718827, 1010.11942618, 1014.47296497],
        [1015.52724228, 1013.64987812, 1014.60438346, 1014.80083918],
        [1018.26562911, 1014.12294633, 1020.59203014, 1015.62677   ]],

       [[1014.90579243, 1011.76844059, 1015.2609588 , 1011.34257804],
        [1013.96184022, 1013.53961123, 1013.51574041, 1011.90345038],
        [1014.73537204, 1012.07217697, 1010.88977935, 1013.52115152]],

       [[1014.5346979 , 1012.99797493, 1011.80784613, 1011.99872311],
        [1015.10907083, 1013.88309907, 1015.05618316, 1013.53284177],
        [1015.87207527, 1015.59608272, 1015.64496147, 1014.64948099]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

In [38]:
named_selection = temps.sel(time= '2018-01-02')
named_selection
# Using .sel() to select data based on coordinate values. This takes at least
# 1 named coordinate and returns data matching said coordinates.

<xarray.DataArray (lat: 3, lon: 4)>
array([[271.01922214, 273.25043174, 273.61887705, 272.83974387],
       [273.04405168, 271.65286474, 273.56231077, 273.33372038],
       [273.46419864, 271.71473318, 273.64877137, 273.49002289]])
Coordinates:
    time     datetime64[ns] 2018-01-02
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [39]:
temps.sel(time= slice('2018-01-01', '2018-01-03'), lon= slice(-110, -70), lat= slice(25, 45))

# In this example,, we are slicing along coordinates for a specific range of times, lats, and lons.

<xarray.DataArray (time: 3, lat: 2, lon: 2)>
array([[[272.39681535, 272.83836254],
        [273.21128587, 274.59331446]],

       [[273.25043174, 273.61887705],
        [271.65286474, 273.56231077]],

       [[272.07816224, 271.74932835],
        [272.69236729, 272.56966262]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 2018-01-03
  * lat      (lat) float64 25.0 40.0
  * lon      (lon) float64 -100.0 -80.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [22]:
temps.loc['2018-01-01']

<xarray.DataArray (lat: 3, lon: 4)>
array([[273.28239724, 272.39681535, 272.83836254, 272.01551886],
       [272.50156357, 273.21128587, 274.59331446, 272.68284241],
       [272.76197732, 273.71141569, 272.89262794, 272.63358187]])
Coordinates:
    time     datetime64[ns] 2018-01-01
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [40]:
temps.loc['2018-01-01':'2018-01-01', 23:45, -110:-70]

# Another selection method, .loc[], similar to pandas

<xarray.DataArray (time: 1, lat: 2, lon: 2)>
array([[[272.39681535, 272.83836254],
        [273.21128587, 274.59331446]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01
  * lat      (lat) float64 25.0 40.0
  * lon      (lon) float64 -100.0 -80.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [42]:
filepath = 'NOAAGlobalTemp_v5.0.0_gridded_s188001_e202212_c20230108T133308.nc'

ds = xr.open_dataset(filepath)
ds

# Importing a dataset into Xarray.

<xarray.Dataset>
Dimensions:  (time: 1716, lat: 36, lon: 72, z: 1)
Coordinates:
  * time     (time) datetime64[ns] 1880-01-01 1880-02-01 ... 2022-12-01
  * lat      (lat) float32 -87.5 -82.5 -77.5 -72.5 -67.5 ... 72.5 77.5 82.5 87.5
  * lon      (lon) float32 2.5 7.5 12.5 17.5 22.5 ... 342.5 347.5 352.5 357.5
  * z        (z) float32 0.0
Data variables:
    anom     (time, z, lat, lon) float32 ...
Attributes: (12/66)
    Conventions:                     CF-1.6, ACDD-1.3
    title:                           NOAA Merged Land Ocean Global Surface Te...
    summary:                         NOAAGlobalTemp is a merged land-ocean su...
    institution:                     DOC/NOAA/NESDIS/National Centers for Env...
    id:                               gov.noaa.ncdc:C00934 
    naming_authority:                 gov.noaa.ncei 
    ...                              ...
    time_coverage_duration:          P143Y0M
    references:                      Vose, R. S., et al., 2012: NOAAs merged ...
    climatology:                     Climatology is based on 1971-2000 monthl...
    acknowledgment:                  The NOAA Global Surface Temperature Data...
    date_modified:                   2023-01-08T18:33:09Z
    date_issued:                     2023-01-08T18:33:09Z